dist: xenial
language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
install:
 - pip install --upgrade pip setuptools
 - pip install --upgrade numpy cython
 - "pip install ."
 - node -v
 - npm install
script:
 - pylint openpifpafwebdemo --disable=fixme
 - npm run lint
 - npm run test
