dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.torch/models
python:
 - "3.5"
 - "3.6"
 - "3.7"
install:
 - pip install --upgrade pip setuptools
 - pip install --upgrade numpy cython
 - "pip install --upgrade .[test]"
 - node -v
 - npm install
script:
#  - pylint openpifpafwebdemo --disable=fixme
 - npm run lint
 - npm run test
