dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/torch/checkpoints
python:
 - "3.6"
 - "3.7"
 - "3.8"
install:
 - pip install --upgrade pip setuptools
 - "pip install --upgrade .[test]"
 - node -v
 - npm install
 - npm run build
 # prefetch model
 - mkdir -p ~/.cache/torch/checkpoints
 - cd ~/.cache/torch/checkpoints; wget -q -nc https://storage.googleapis.com/openpifpaf-pretrained/v0.8.0/shufflenetv2x1-pif-paf-edge401-190705-151607-d9a35d7e.pkl; cd -
script:
 - pylint openpifpafwebdemo --disable=fixme
 - npm run lint
 - npm run test
